name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Discord notification
        env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
            args: '@here | The project {{ EVENT_PAYLOAD.repository.full_name }} has been updated in main.\nCommit Message:\n||EVENT_PAYLOAD.github.event.head_commit.message||'