name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Discord notification
        env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
            args: '@here | The project *{{ EVENT_PAYLOAD.repository.full_name }}* has been updated in main. User: *{{ EVENT_PAYLOAD.head_commit.author.name }}* Commit Message: *{{ EVENT_PAYLOAD.head_commit.message }}*'